### ISSUE TITLE
Pod xxxx was not created by a job, ignoring.

### ISSUE THREAD

**Issue by SqiSch** [lwolf/kube-cleanup-operator#15]
He Sergey,
i always get the message: 
```
Pod xxxx was not created by a job, ignoring.
```
We running kubernetes 1.9.6 on google container engine.  
Our job manifest f.e.:
```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: behat
    chart: behat-1.0
.....
``` 

a describe of a succeeded pod
```
Name:           behat-d6048dbd-815e-4116-8bf1-71b2ae45c22b-32-8qxpp
Namespace:      default
Labels:         app=behat
                controller-uid=52ae430b-3bd1-11e8-9134-42010a840081
                job-name=behat-d6048dbd-815e-4116-8bf1-71b2ae45c22b-32
.....
Status:         Succeeded
Controlled By:  Job/behat-d6048dbd-815e-4116-8bf1-71b2ae45c22b-32
......

    State:          Terminated
      Reason:       Completed
```

do you have any clues why the problem here occurs?

Best, 
Marcel
