### ISSUE TITLE
add multiarch docker build

### ISSUE THREAD

**Issue by lwolf** [lwolf/kube-cleanup-operator#21]
Add support for multiarch docker manifests

**Comment by Rick-Jongbloed** [comment]
Just fyi, i've got an ARM build build by drone here: https://github.com/Rick-Jongbloed/kube-cleanup-operator-arm. It might help you to get ARM support build in  🥇

**Comment by lwolf** [comment]
@Rick-Jongbloed  that's cool, thank you

**Comment by zentavr** [comment]
Hello @lwolf. Kindly asking when that build might be available?

**Comment by matthewwalk** [comment]
Just want to follow up with a similar solution to @Rick-Jongbloed's. This one is a CircleCI  job using the aws-ecr orb.

```yaml
  build-push-cleanup-operator:
    machine:
      image: ubuntu-2204:2024.01.1
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - run:
          name: Download and modify kube-cleanup-operator
          command: |
            sudo apt-get update && \
            sudo apt-get install -y git make unzip
            git clone https://github.com/lwolf/kube-cleanup-operator .
            sed -i 's;GOARCH=amd64;GOARM=7 GOARCH=arm;g' Makefile
            sed -i 's;FROM alpine;FROM arm64v8/alpine;g' Dockerfile
      - aws-ecr/build-and-push-image:
          checkout: false
          repo: kube-cleanup-operator
          registry-id: AWS_ACCOUNT_ID
          create-repo: true
          tag: 'kube-cleanup-operator'
          platform: 'linux/arm64'
  ```
