### ISSUE TITLE
cleanup also pods completed

### ISSUE THREAD

**Issue by haarchri** [lwolf/kube-cleanup-operator#57]
hello, is it possible to get more function that we can also cleanup pods wich are completed for configurable time ?

**Comment by haarchri** [comment]
We have a lot of pods in an OpenShift Environment (Build Pods) wich are in Status Completed but not auto removed from Cluster - so it would great to See that the cleanup pod can also remove those

**Comment by lwolf** [comment]
depends on who owne those pods and how they were created, you might be able to clean those by using
```
-delete-orphaned-pods-after duration
        Delete orphaned pods. Pods without an owner in non-running state (golang duration format, e.g 5m), 0 - never delete
```

**Comment by haarchri** [comment]
looks like the pods have a owner reference:

```
  ownerReferences:
    - apiVersion: build.openshift.io/v1
      controller: true
      kind: Build
```
